### ISSUE TITLE
Error: Request failed with status code 503

### ISSUE THREAD

**Issue by hgareeballa** [karataev/fetch-data-patterns#1]
Hi
i keep getting below error even when i changed the chunk size to 10,
if i change the getidlist to any think below 100 it works fine !

---
(node:20608) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503
    at createError (C:\node\fetch-data-patterns-master\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\node\fetch-data-patterns-master\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\node\fetch-data-patterns-master\node_modules\axios\lib\adapters\http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:20608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:20608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by karataev** [comment]
503 means that service is unavailable. Maybe it can't handle a lot of simultaneous requests. In this case try to lower the chunk size or make API requests in series.
